name: CI

on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [12.x]
        os: [macos-latest]


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt' # See 'Supported distributions' for available options
        java-version: '8'

    - name: Install cordova
      run: npm install -g cordova@10.0.0

    - name: Install cordova paramedic
      run: npm install -g apache/cordova-paramedic#e99fd38

    - name: uninstall build-tools 31
      run: sdkmanager --uninstall 'build-tools;31.0.0'

    - name: install build-tools 31
      run: sdkmanager --install 'build-tools;30.0.3'

    - name: npm install
      run: |
        npm i
    - name: build android
      run: |
        cordova-paramedic --platform android@10.0.1 --plugin . --justbuild --verbose
