name: CI

on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [12.x]
        os: [macos-latest]


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt' # See 'Supported distributions' for available options
        java-version: '8'

    - name: Install cordova
      run: sudo npm install -g cordova

    - name: Install cordova paramedic
      run: sudo npm install -g cordova-paramedic

    - name: npm install
      run: |
        npm i
    - name: build android and ios
      run: |
        cordova-paramedic --platform android --plugin . --justbuild --verbose
        cordova-paramedic --platform ios --plugin . --justbuild --verbose --timeout 900000
